version: 0.0
os: linux
files:
  - source: /
    destination: /app

hooks:
  AfterInstall:
    - location: install_dependencies
      timeout: 300
      runas: root
  ApplicationStart:
    - location: run
      timeout: 300
      runas: root
  ApplicationStop:
    - location: stop
      timeout: 300
      runas: root
