version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: install_dependencies
      timeout: 300
      runas: root
    - location: run
      timeout: 300
      runas: root
  ApplicationStop:
    - location: stop
      timeout: 300
      runas: root
